name: Keep Render App Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Service to Become Alive
        run: |
          URL="https://test-fn50.onrender.com/"
          echo "Checking if service is alive..."
          until curl -s -o /dev/null -w "%{http_code}" "$URL" | grep -q "200"; do
            echo "Service is down, retrying in 10 seconds..."
            sleep 10
          done
          echo "Service is up and running!"
