name: Keep Render App Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Keep Alive
        run: curl -s -o /dev/null -w "%{http_code}" https://test-fn50.onrender.com/
