name: Test Proxies
on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:        # Allow manual triggering
# Add explicit permissions to allow pushing to the repository
permissions:
  contents: write
jobs:
  test-proxies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Test proxies
        run: |
          python - << EOF
          import json
          import requests
          import concurrent.futures
          import time
          
          def test_proxy(proxy):
              try:
                  proxies = {
                      "http": f"http://{proxy}",
                      "https": f"http://{proxy}"
                  }
                  
                  # More comprehensive testing - check actual IP address
                  response = requests.get("https://api.ipify.org", 
                                          proxies=proxies, 
                                          timeout=15)
                  
                  # Verify we actually got a response and the proxy is truly working
                  if response.status_code == 200 and len(response.text.strip()) > 0:
                      # Try to get location info
                      try:
                          location_response = requests.get("https://ipinfo.io/json",
                                                          proxies=proxies,
                                                          timeout=15)
                          location_data = location_response.json()
                          country = location_data.get('country', 'Unknown')
                          city = location_data.get('city', 'Unknown')
                          
                          print(f"Proxy {proxy} is working. IP: {response.text.strip()}, Location: {city}, {country}")
                          
                          # Add location data to return value
                          return {
                              "proxy": proxy,
                              "ip": response.text.strip(),
                              "country": country,
                              "city": city,
                              "region": location_data.get('region', 'Unknown')
                          }
                      except Exception as e:
                          print(f"Proxy {proxy} is working (IP: {response.text.strip()}) but location check failed: {str(e)}")
                          return {
                              "proxy": proxy,
                              "ip": response.text.strip(),
                              "country": "Unknown",
                              "city": "Unknown",
                              "region": "Unknown"
                          }
                  else:
                      print(f"Proxy {proxy} returned status code {response.status_code}")
                      return None
              except Exception as e:
                  print(f"Proxy {proxy} failed: {str(e)}")
                  return None
          
          # Fetch the proxy list
          try:
              response = requests.get("https://raw.githubusercontent.com/Shashwat-CODING/yt/refs/heads/main/proxy.json")
              data = response.json()
              proxy_list = data.get("proxies", [])
              print(f"Found {len(proxy_list)} proxies to test")
          except Exception as e:
              print(f"Error fetching proxy list: {str(e)}")
              proxy_list = []
          
          # Test all proxies in parallel, but with fewer concurrent workers to avoid rate limits
          working_proxies = []
          with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
              future_to_proxy = {executor.submit(test_proxy, proxy): proxy for proxy in proxy_list}
              for future in concurrent.futures.as_completed(future_to_proxy):
                  result = future.result()
                  if result:
                      working_proxies.append(result)
          
          # Save working proxies to wpr.json with more detailed information
          working_data = {"proxies": [p["proxy"] for p in working_proxies], 
                          "details": working_proxies}
          with open("wpr.json", "w") as f:
              json.dump(working_data, f, indent=2)
          
          print(f"Found {len(working_proxies)} working proxies out of {len(proxy_list)}")
          EOF
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add wpr.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update working proxies list" && git push)
